### ISSUE TITLE
Local evaluator for AMOD not working

### ISSUE THREAD

**Issue by alezana** [duckietown/duckietown-challenges-runner#1]
when running `dts challenges evaluate` for AMOD I get
```shell
ERROR:dts:Cannot get container local-evaluator: 404 Client Error: Not Found ("No such container: local-evaluator")
```
It was working smoothly ~1 week ago when I used it a bit and nothing changed on my system. I also tried to purge all docker images and containers but no effect.

Anyway, I tried then to use `dt-challenges-evaluate-local` but I get 
```shell
Successfully built 799ec7031d76
Successfully tagged myimage:latest
INFO:runner-local:steps: [u'step1-simulation', u'step2-scoring']
INFO:runner-local:Now considering step "step1-simulation"
DEBUG:evaluator:Running: docker-compose -p project58 config
DEBUG:evaluator:Saving stdout to /tmp/tmp4yleDP/docker-stdout.txt
ERROR:runner-local:Traceback (most recent call last):
  File "/home/ale/.local/lib/python2.7/site-packages/duckietown_challenges_runner/runner_local.py", line 35, in runner_local_main
    runner_local_main_()
  File "/home/ale/.local/lib/python2.7/site-packages/duckietown_challenges_runner/runner_local.py", line 160, in runner_local_main_
    do_pull=do_pull)
  File "/home/ale/.local/lib/python2.7/site-packages/duckietown_challenges_runner/runner.py", line 453, in run_single
    config_validated = run_docker(wd, project, ['config'], get_output=True)
  File "/home/ale/.local/lib/python2.7/site-packages/duckietown_challenges_runner/runner.py", line 879, in run_docker
    return subprocess.check_output(cmd0, cwd=cwd, stderr=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by andy2804** [comment]
I do experience the same error as alezana when trying to run dts challenges evaluate.
It worked smoothly before, but whenever I try to debug my code and it crashes due to some bugs in my submission, the container stops and then I start experiencing this error.

**Comment by AndreaCensi** [comment]
Can you provide a commit in which this happens? Cannot reproduce.

On my machine, the python template works, but not the java one.
